### ISSUE TITLE
Add in-game screenshot

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.mrarm.mcpelauncher#1]
It would be great if there was an actual gameplay screenshot in the AppStream metadata.

**Comment by ChristopherHX** [comment]
I added one ingame screenshot of an ancient Nether Portal https://github.com/flathub/io.mrarm.mcpelauncher/commit/077a54e354885e229edea9d6c8837b6029372b59#diff-61a1b5dd6d93ec539ec48e59e63205caR29
in the AppStream metadata.
![image](https://user-images.githubusercontent.com/44845461/86053073-3f4b2880-ba58-11ea-8a73-6d16ef2785d8.png)

**Comment by AsciiWolf** [comment]
Thanks!
