### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by TheNewsYorkTime** [flathub/io.mrarm.mcpelauncher#121]
Wayland is not supported. It crashes when being run on Wayland. Please add Wayland support. I'm trying to run it on my Chromebook, which uses Wayland by default. It would be nice to have it work by default.

**Comment by tristann21** [comment]
Wayland seems to be working completely fine for me on Bazzite Linux, running KDE 6. No XWayland.

**Comment by TheNewsYorkTime** [comment]
I'll recheck / do more testing tomorrow.

**Comment by tristann21** [comment]
> I'll recheck / do more testing tomorrow.

iirc, chrome os uses just a generic debian vm when enabling "linux mode" or whatever it is, so just something to consider and why you might run into problems. it's not really "linux".

**Comment by TheNewsYorkTime** [comment]
It works, I do have other issues, but those are for other issue threads.
