### ISSUE TITLE
searching in marketplace exits with the code 6 50% of the time

### ISSUE THREAD

**Issue by B00bleaTea** [flathub/io.mrarm.mcpelauncher#18]
i tried searching on the marketplace search and my game sudenly crashed and exited with the code 6, i'm on fedora 33 and i am running 1.16.200.1 from google play.

**Comment by ChristopherHX** [comment]
Sorry, but I need far more information than you provided.

You said 
> exits with the code 6 50% of the time

You provided neither a crashlog nor a reproduceable instruction to get a crash, on my PC the same game never crashed while searching in the unsupported marketplace on archlinux with different hardware.

For further reference my Hardware CPU + GPU
```
Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 
Mesa Intel® UHD Graphics 620 (KBL GT2)
```

_How well does the Minecraft Version work on android x86_64?, If it crashs there to report it to mojang_
