### ISSUE TITLE
Can't find source path /tmp/.X11-unix/X0: No such file or directory

### ISSUE THREAD

**Issue by jumpmanjohn** [flathub/io.mrarm.mcpelauncher#20]
i use flatpak and when i restarted to enable pointer lock Can't find source path /tmp/.X11-unix/X0: No such file or directory
came up. ive redone the process and ive sometimes powerwashed my chromebook to get it to work again. but after a reset it doesnt work. any fixes?

**Comment by ChristopherHX** [comment]
Restart the whole chromebook again? like suggested here
https://github.com/flatpak/flatpak/issues/938

_Never happend to me_,I just searched `Can't find source path /tmp/.X11-unix/X0` in a search engine.

If nothing helps....
The AppImage version of the launcher is _currently_ [here](https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/ng.appimage), it's an alternative for the flatpak version.

**Comment by ChristopherHX** [comment]
Also the issue author never replied...
