### ISSUE TITLE
License error using .apk file.. 

### ISSUE THREAD

**Issue by Haus3master** [flathub/io.mrarm.mcpelauncher#21]
Hello, I have been trying to install and play minecraft pe 1.16.200.02 which is fully supported and is playable on ng appimage .617 to be exact and anything above that results in a license error, that's why, I tired installing the flatpak version but this issue is persistent, here are a few images regarding this, the launcher is the flatpak version... 
![IMG_2021-02-28-00-01-55-131](https://user-images.githubusercontent.com/66825701/109396902-e078de80-7959-11eb-80c7-eb61b5415c44.jpg)
![IMG_2021-02-28-00-02-44-334](https://user-images.githubusercontent.com/66825701/109396909-e8388300-7959-11eb-9f97-1adcf8fe40de.jpg)
And then, the second screenshot is the result of launching with the flatpak launcher and any appimage launcher above the .617 version...
PS: I'm ready to provide further logs and info and will be more than happy to test anything you ask me to...
Edit: My PC is the raspberry Pi 3B+ running raspberry Pi OS 32bit...

**Comment by ChristopherHX** [comment]
**This launcher was abused by piracy sites**, I took action
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/209#issuecomment-786889470

**Comment by Haus3master** [comment]
Oh, okay, thanks for the info, really appreciate it, I was previously screen to login with my actual account for reasons, well, now I'll log in with my actual account...
