### ISSUE TITLE
Realm bug (maybe multiplayer bug to.)

### ISSUE THREAD

**Issue by edisnttechsavy** [flathub/io.mrarm.mcpelauncher#22]
There is a realm bug. I do not know what it is, as a was told to contact the developers when shown to someone. (I do not now how.)
I am not sure what this is though, I tried closing it again, but it didn't seem to work. (note: as my name says... I am NOT tech savvy)

https://gm1.ggpht.com/YfSyEsk-vzH--CJ9SmWNFS4rwbHkxeIzWqY59ANMNML-1NP8wqnGZA2rCum7Dm32xgWv30HJYbqD4LWvnxEAuSbVuG5O4IsEqdx_aRTv2DOFJGFr-N0pU9opeSTQhUPChA22yIRn0EgKqkKgj7LsmMn5o67K0V88r_QU9NpEVOQ99J8PDA1GItxHSAa23lkIBDD3CsA1_Qpq5L2wc6iHeEqW8QjvQbGhDHh-5NvUHme09rRFTeNW3r4de6puFL3p6IeNPhdGeRk7Q33YZb7JuAKx5fEUMFZEwlhvExBesFaGr-IRRhLkEot2V_eOLdC5cfRDoDAYuFoDTLK7mUzwBt_F1nMzPSXpttI3lUtT-lC70a_uqR5lVb8jLGRWJihm4FtQ_DMjiaPvh7davcOwY6wrKrcagwOa5634vel9jf6ybgyNkfA6HgrWshNeH-pdWmyp3KDyUqCjzfpOkhSdKJf68rVK-yn1rL-uJdyUy0GpFflJaGF7kjiiCVeqYJ4H2wysDZmpQXpMousCr3IiZZB0fuKB-c9g8MuOE33Z0arT08xJ7zA4PkOhmc-z181bYts89j7gQz47weixpH_yxGH4sRwLe95vZ35BtCQ-V69z1rf1i5vxawZfNCerXcg_GGb8yueSGtNm26Y9l-vzRzxsJ4Xz033WfLm03Zgr1tMVEF7hgSle2Nu99JJFFNjQMNTpgOH_kw4P62NC9ZxbC5jpnDsOBrXpjIpAssW93359SQt5x9KzaztsPliMNCziCCbiPZ8=s0-l75-ft-l75-ft

**Comment by ChristopherHX** [comment]
Just wan't to metion I would say 1.16.210 don't really work but it opens...
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-803468474

@edisnttechsavy Do you want to try it again?

**Comment by edisnttechsavy** [comment]
Yeah I'll try.

**Comment by ChristopherHX** [comment]
I recommend to not purchase realms, because there is no warranty that realms will continue to work. Also I never ever tested that realms are working in this launcher.
