### ISSUE TITLE
Update for 1.16.210.05?

### ISSUE THREAD

**Issue by JumperLuko** [flathub/io.mrarm.mcpelauncher#23]
It is not possible to play in the latest version.

This error appears:
"Your previously downloaded Minecraft Version might be unsupported or just corrupted.
if you wanted to play a Beta or a new Release please wait patiently for an update,
please choose a compatible version from the profile Editor
otherwise if you have updated the Launcher recently.
e.g. a crash please delete it in Settings,
then download it again via the updated Launcher."

If I can do something to help

**Comment by jason1234rule** [comment]
I am also having this problem.  Is anyone aware of a solution?

**Comment by Haus3master** [comment]
No, the launcher needs an update on order to get newer versions working, so, we just have to wait a bit...

**Comment by JumperLuko** [comment]
> No, the launcher needs an update on order to get newer versions working, so, we just have to wait a bit...

Yap, thanks for the phenomenal work ~<3

**Comment by jason1234rule** [comment]
Ok, hope they come out with fix soon.

**Comment by ChristopherHX** [comment]
Just wan't to metion I would say 1.16.210 don't really work but it opens...
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48#issuecomment-803468474

**Comment by ChristopherHX** [comment]
There is no reason, to keep this open.
