### ISSUE TITLE
When I download and play 1.16.210 the screen becomes black.

### ISSUE THREAD

**Issue by lol851** [flathub/io.mrarm.mcpelauncher#30]
when I click the green button the play one when it loads up the screen is just black. does this happen to anybody else?

**Comment by ChristopherHX** [comment]
Have you tried the AppImage? I mean some graphic driver setups won't work with the flatpak, like ancient nvidia cards from 2012.
Find it here: https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/v0.1-beta-21-648

Download the Launcher for your device type (`.AppImage`), then
`chmod +x /path/to/AppImage`
Now you can double click it or type `/path/to/AppImage`

> the screen becomes black.

The whole screen or only the Game?

**Comment by lol851** [comment]
only the game

**Comment by ChristopherHX** [comment]
> this game log pop up.

Post the Content of the game log popup (Button top right to copy the text)? or we can close this.

**Comment by lol851** [comment]
![Screenshot 2021-03-23 12 18 52](https://user-images.githubusercontent.com/81200808/112180513-02205b00-8bd2-11eb-9900-484a753ed2ec.png)
![Screenshot 2021-03-23 12 19 03](https://user-images.githubusercontent.com/81200808/112180542-08163c00-8bd2-11eb-8bf3-8fe8b81bf15f.png)
 those are the game log and black screen.

**Comment by ChristopherHX** [comment]
The log has no text???, I have no idea whats going wrong..
If the log would have text then at least more information about your issue would be available.

It seem to work for a lot of users, I don't know the details of your Operating System Confirguration and hardware.

Still please try the AppImage I linked previously.

_Sorry, but It is unlikly that this issue will be resolved_

**Comment by lol851** [comment]
alright thankyou

**Comment by lol851** [comment]
Though for some reason when i type the commands it just said no such file or directory.

**Comment by lol851** [comment]
Never mined I got it to work by myself!
