### ISSUE TITLE
Switch to keyboard / mouse only on Linux?

### ISSUE THREAD

**Issue by trini** [flathub/io.mrarm.mcpelauncher#31]
Running this on Linux, in order to have access to Bedrock edition severs and friends lists (so "just use Java edition" isn't an option), and I can't see how to disable controller support.  Manually editing the options.txt file I can toggle "full keyboard support" option to be enabled, but once runnning LB/RB are needed to change tabs between Local/Friends/Servers and if you join a server controller is required to "use" and so forth, rather than mouse.

**Comment by ChristopherHX** [comment]
You can do that with the flatpak.
Please read this,
https://github.com/ChristopherHX/mcpelauncher-manifest/issues/150#issuecomment-727053076

**Comment by trini** [comment]
@ChristopherHX Thanks, that did what I wanted.  Perhaps a FAQ entry for the next person?
