### ISSUE TITLE
Realms doesn't seem to work

### ISSUE THREAD

**Issue by lol851** [flathub/io.mrarm.mcpelauncher#32]
It seems as if when I try to purchase realms this happens.
![Screenshot 2021-03-31 12 13 38](https://user-images.githubusercontent.com/81200808/113176578-a3369380-921a-11eb-99c6-ff4d1bd1e31a.png)

**Comment by lol851** [comment]
also, i am connected to the internet and I have no internet problems.

**Comment by ChristopherHX** [comment]
Please don't use realms and the store with this launcher.I'm not willing to fix any issues you are hitting while using these features of the game.However it might work if you buy the subscription on a real android device (or Vm, other bedrock) with the same Microsoft account. Don't tell me later I haven't warned you.

**Comment by lol851** [comment]
ok
