### ISSUE TITLE
Touch Controls will not activate

### ISSUE THREAD

**Issue by acerchromebook** [flathub/io.mrarm.mcpelauncher#39]
Hello,
I have an acer N16Q14 chromebook with a touch screen. I just used flatpak to install minecraft bedrock, I can't seem to get the on screen touch controls to work. I used the bulit in linux function on the chromebook.
Any help is appericated.

**Comment by ChristopherHX** [comment]
Please consider switching to the [AppImage of the Launcher](https://github.com/ChristopherHX/linux-packaging-scripts/releases), it has touch control and 32bit minecraft support. I have no plans to add it in the flatpak version.

I tried to use the same window provider in the flatpak, but it had missing dependencies to udev.

**Comment by acerchromebook** [comment]
I am new at this is that the only command I have to run?
