### ISSUE TITLE
[Bug] Imported Skins Don't Save

### ISSUE THREAD

**Issue by Max-Rodriguez** [flathub/io.mrarm.mcpelauncher#44]
Whenever I launch bedrock, I have to re-import my custom skin image since it goes back to the default skin every time I launch. This has been happening, even after I recently wiped out my disk and reinstalled Linux.

Here is my OS specifications:

Linux Distribution: Fedora Workstation 34
Windowing manager: Mutter (XWayland)
Desktop Environment: GNOME 40.1
Intel Core i7, 8 gigs of memory installed

**Comment by ChristopherHX** [comment]
Selecting Minecraft <= 1.16.201 will load skin's correctly (in most cases).
Possible related to the not working marketplace in the same version.

_It is hard to debug, we don't have the source code of the game_

**Comment by Max-Rodriguez** [comment]
Ah I forgot, yeah makes sense. Thanks for the workaround suggestion.
