### ISSUE TITLE
minecraft linux launcher

### ISSUE THREAD

**Issue by TH4T** [flathub/io.mrarm.mcpelauncher#46]
when using the unofficial linux launcher i am having issues as when i sign into an account which has purchased minecraft pocket edition then go to versions there is nothing there and when i try to install from the launcher option it says error 405 and when i try to update the launcher it just gets stuck

**Comment by ChristopherHX** [comment]
> launcher option it says error 405

I'm a bit confused?
You said update stuck, but the flatpak is the only version which doesn't even have an in app Updater.
Also the http 405 issue is only known in the armhf-Appimage and was never an issue in the armhf-flatpak.

Which version of the launcher are you using? (Screenshot of settings -> About)

**Comment by TH4T** [comment]
> only

im not really sure to be honest i wastold to come here for my issues by a youtuber the ink to his viedo i:
https://www.youtube.com/watch?v=jkQB9maWGI0
