### ISSUE TITLE
Upgrade KDE runtime?

### ISSUE THREAD

**Issue by ranchester2** [flathub/io.mrarm.mcpelauncher#54]
Is there any reason this is still using 5.14? Other apps use newer ones, and it doesn't seem ideal to have to install this older version just for one application.

So I think this really should just use 5.15 instead.

**Comment by ChristopherHX** [comment]
Blocked by arm32 removal from sdk kde 5.15.
How can I upgrade the sdk for amd64 and arm64, but keep using the old one for arm32?
https://github.com/flathub/io.mrarm.mcpelauncher/pull/6#issue-480606943

So if I merge my PR from last year then you get an outdated version on an arm32 device, there is no automatic way to deprecate and remove one architecture from flathub.

**Comment by ranchester2** [comment]
The 5.14 runtime's 19.08 freedesktop extensions (like gl and vaapi) are now EOL since this september, so this is more of an issue now. And apparently the 5.14 runtime should also now be eol since september, but I am not getting any eol warnings for it

**Comment by barthalion** [comment]
> So if I merge my PR from last year then you get an outdated version on an arm32 device, there is no automatic way to deprecate and remove one architecture from flathub.

Please open an issue about it at https://github.com/flathub/flathub and I will handle the arm32 build deprecation from infrastructure's end.

**Comment by ChristopherHX** [comment]
I updated the kde runtime now.
However building it implicitly depends on another EOL runtime (`The Freedesktop SDK 18.08`) (Log https://flathub.org/builds/#/builders/5/builds/4718/steps/5/logs/stdio)
```
flatpak --user install --or-update --noninteractive flathub org.flatpak.flat-manager-client
 in dir /srv/buildbot/worker/build-aarch64-3/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'flatpak', b'--user', b'install', b'--or-update', b'--noninteractive', b'flathub', b'org.flatpak.flat-manager-client']
 using PTY: False
Info: org.freedesktop.Platform is end-of-life, with reason: The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs is end-of-life, with reason: The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.Locale is end-of-life, with reason: The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
program finished with exit code 0
```
See https://github.com/flathub/org.flatpak.flat-manager-client/issues/1

Technically is the kde runtime 5.15 also EOL, because qt 5.15 is EOL for opensource software ( [updates only for paying companies](https://wiki.qt.io/Qt_5.15_Release) ).

**Comment by ChristopherHX** [comment]
Ugh, I need to revert the change downloading the game is completely broken now (progress bar is frozen at 0%). This did even work with qt 6.2 beta.

**Comment by ChristopherHX** [comment]
Fixed and replaced the broken source code for flatpak. I still don't know why it was broken, since it worked on every other configuration I have tested so far.
