### ISSUE TITLE
EOL?

### ISSUE THREAD

**Issue by vchernin** [flathub/io.mrarm.mcpelauncher#69]
Unfortunately this project looks to no longer be [maintained upstream](https://github.com/ChristopherHX/mcpelauncher-manifest/issues/48). If no one steps up to maintain it relatively soon, this repository should be set to [EOL](https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life).

**Comment by ChristopherHX** [comment]
Oh yes, with the exception that I don't want to archive this repository yet.

At least I want to publish https://github.com/minecraft-linux/mcpelauncher-manifest/releases/tag/v0.3.2 before setting it EOL.

I may add support of 1.18.10 in ca. a Year, but I have no plans to keep up with mojang anymore.

**Comment by ChristopherHX** [comment]
I added the EOL marker to arm64 and amd64 tbc.

However arm32 still don't have one, upload failed with http 500.

**Comment by Max-Rodriguez** [comment]
Well thank you for maintaining the package while it lasted, it worked pretty well for me and was cool running MCPE on Linux. Not sure what specifically caused the decision for EOL, saw something about a violation of the GPL v3 license, but thank you for contributing your work 👍🏼

**Comment by ChristopherHX** [comment]
...6 month later, this flatpak gets an update. Probably without any changes what some wants to have.
